sudo: false
language: node_js
node_js:
    - 19
services:
    - mongodb
cache:
    directories:
        - node_modules
script:
    - npm run build
# Note: I am commenting this line out because I am not running any automatic tests.
#    - npm run test
